var questionsLeft = '['+ question + ' questions Left]';
var adjective = prompt('Please type an adjective ' + questionsLeft);
question -= 1;
questionsLeft = '[' + question + 'questions Left]';
var verb = prompt('Please type a verb' + questionsLeft);
question -= 1;
questionsLeft = '[' + question + 'questions Left]';
var noun = prompt('Please type a noun' + questionsLeft);
alert('All done. Ready for the message?');
var sentence = "<h2>There once was a " + adjective;
sentence += ' programmer who wanted to use JavaScript to ' + verb;
sentence += ' the ' + noun + '.</h2>';
document.write(sentence);
